name: Secrets

on:
  pull_request:
    branches: ["main"]

jobs:
     echo:
       name: Echo
       runs-on: ubuntu-latest
       steps:
         - name: Hello world
           run: echo ${{ secrets.SOME_SECRET }}
      
